### ISSUE TITLE
Error Running on Ubuntu 20.04 (WSL2)

### ISSUE THREAD

**Issue by jtdub** [nautobot/nautobot-lab#4]
```$ docker logs nautobot
2021-03-05 15:14:48,528 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2021-03-05 15:14:48,529 INFO supervisord started with pid 7
2021-03-05 15:14:49,535 INFO spawned: 'nautobot' with pid 9
2021-03-05 15:14:49,542 INFO spawned: 'nautobot-rq' with pid 10
2021-03-05 15:14:49,543 INFO spawned: 'postgresql-server' with pid 11
2021-03-05 15:14:49,544 INFO spawned: 'redis-server' with pid 12
2021-03-05 15:14:50,599 INFO success: postgresql-server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-03-05 15:14:50,599 INFO exited: nautobot (exit status 1; not expected)
2021-03-05 15:14:50,608 INFO exited: nautobot-rq (exit status 1; not expected)
2021-03-05 15:14:51,610 INFO spawned: 'nautobot' with pid 23
2021-03-05 15:14:51,612 INFO spawned: 'nautobot-rq' with pid 24
2021-03-05 15:14:52,634 INFO success: redis-server entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
2021-03-05 15:14:52,634 INFO exited: nautobot (exit status 1; not expected)
2021-03-05 15:14:52,638 INFO exited: nautobot-rq (exit status 1; not expected)
2021-03-05 15:14:54,641 INFO spawned: 'nautobot' with pid 31
2021-03-05 15:14:54,642 INFO spawned: 'nautobot-rq' with pid 32
2021-03-05 15:14:55,663 INFO exited: nautobot-rq (exit status 1; not expected)
2021-03-05 15:14:55,665 INFO exited: nautobot (exit status 1; not expected)
2021-03-05 15:14:58,669 INFO spawned: 'nautobot' with pid 39
2021-03-05 15:14:58,671 INFO spawned: 'nautobot-rq' with pid 40
2021-03-05 15:14:59,628 INFO exited: nautobot-rq (exit status 1; not expected)
2021-03-05 15:14:59,631 INFO gave up: nautobot-rq entered FATAL state, too many start retries too quickly
2021-03-05 15:14:59,631 INFO exited: nautobot (exit status 1; not expected)
2021-03-05 15:14:59,948 INFO gave up: nautobot entered FATAL state, too many start retries too quickly
```

```
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/nautobot/core/cli.py", line 55, in main
    run_app(
  File "/usr/local/lib/python3.8/dist-packages/nautobot/core/runner/runner.py", line 268, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.8/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/dist-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/usr/local/lib/python3.8/dist-packages/nautobot/extras/apps.py", line 19, in ready
    wrap_model_clean_methods()
  File "/usr/local/lib/python3.8/dist-packages/nautobot/extras/plugins/validators.py", line 43, in wrap_model_clean_methods
    for model in ContentType.objects.filter(FeatureQuery("custom_validators").get_query()):
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 287, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.8/dist-packages/cacheops/query.py", line 273, in _fetch_all
    return self._no_monkey._fetch_all(self)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/dist-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  the database system is starting up
FATAL:  the database system is starting up
```

```
root@dfb2d8cac4e8:/opt/nautobot# cat postgres-error.log
2021-03-05 15:17:28.086 CST [11] LOG:  starting PostgreSQL 12.6 (Ubuntu 12.6-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
2021-03-05 15:17:28.087 CST [11] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-03-05 15:17:28.087 CST [11] LOG:  could not bind IPv6 address "::1": Cannot assign requested address
2021-03-05 15:17:28.087 CST [11] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2021-03-05 15:17:28.098 CST [11] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-03-05 15:17:28.119 CST [16] LOG:  database system was interrupted; last known up at 2021-03-05 14:47:03 CST
2021-03-05 15:17:28.863 CST [19] nautobot@nautobot FATAL:  the database system is starting up
2021-03-05 15:17:28.864 CST [21] nautobot@nautobot FATAL:  the database system is starting up
2021-03-05 15:17:28.865 CST [20] nautobot@nautobot FATAL:  the database system is starting up
2021-03-05 15:17:28.865 CST [22] nautobot@nautobot FATAL:  the database system is starting up
2021-03-05 15:17:30.856 CST [27] nautobot@nautobot FATAL:  the database system is starting up
2021-03-05 15:17:30.856 CST [29] nautobot@nautobot FATAL:  the database system is starting up
2021-03-05 15:17:30.857 CST [28] nautobot@nautobot FATAL:  the database system is starting up
2021-03-05 15:17:30.857 CST [30] nautobot@nautobot FATAL:  the database system is starting up
2021-03-05 15:17:33.808 CST [35] nautobot@nautobot FATAL:  the database system is starting up
2021-03-05 15:17:33.808 CST [36] nautobot@nautobot FATAL:  the database system is starting up
2021-03-05 15:17:33.808 CST [37] nautobot@nautobot FATAL:  the database system is starting up
2021-03-05 15:17:33.808 CST [38] nautobot@nautobot FATAL:  the database system is starting up
2021-03-05 15:17:37.835 CST [43] nautobot@nautobot FATAL:  the database system is starting up
2021-03-05 15:17:37.835 CST [44] nautobot@nautobot FATAL:  the database system is starting up
2021-03-05 15:17:37.836 CST [45] nautobot@nautobot FATAL:  the database system is starting up
2021-03-05 15:17:37.836 CST [46] nautobot@nautobot FATAL:  the database system is starting up
2021-03-05 15:17:38.866 CST [16] LOG:  database system was not properly shut down; automatic recovery in progress
2021-03-05 15:17:38.872 CST [16] LOG:  redo starts at 0/16486C0
2021-03-05 15:17:38.902 CST [16] LOG:  invalid record length at 0/1A5DC68: wanted 24, got 0
2021-03-05 15:17:38.902 CST [16] LOG:  redo done at 0/1A5DC40
2021-03-05 15:17:39.804 CST [11] LOG:  database system is ready to accept connections
```

Essentially `supervisord` is giving up on `nautobot` before `postgresql` has completely started up.

**Comment by jtdub** [comment]
#14 fixed this issue. Whoop!
